apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
 
  labels:
    app: my-app
spec:
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels: 
        app: my-app
    spec:
      containers:
      - name: myapp-container
        image: 7205416852/my_ip:latest
        ports:
        - containerPort: 5000